Repository MarimerLLC/csla, pull requests merged in 2024-06, with the labels that each got.

#3977 Add .ConfigureAwait(false) on (thread) context irrelevant operations
  Source/Csla.Blazor.WebAssembly/State/SessionManager.cs
  Source/Csla/DataPortalClient/DataPortalProxy.cs
  Source/Csla/DataPortalClient/HttpProxy.cs
Labels: kind/enhancement

#3983 Improve IsSavable performance
  Source/Csla/BusinessBindingListBase.cs
  Source/Csla/BusinessListBase.cs
  Source/Csla/Core/BusinessBase.cs
Labels: kind/enhancement

#3979 Make WaitForIdle() methods virtual so a user can extend it's functionality
  Source/Csla/BusinessBase.cs
  Source/Csla/BusinessBindingListBase.cs
  Source/Csla/BusinessListBase.cs
  Source/Csla/Core/BusinessBase.cs
  Source/Csla/Core/BusyHelper.cs
  Source/Csla/Core/ExtendedBindingList.cs
  Source/Csla/Core/ObservableBindingList.cs
  Source/Csla/DynamicBindingListBase.cs
  Source/Csla/DynamicListBase.cs
  Source/Csla/NameValueListBase.cs
  Source/Csla/ReadOnlyBindingListBase.cs
  Source/Csla/ReadOnlyListBase.cs
Labels: kind/enhancement

#4002 Changed missing other WaitForIdle implementations
  Source/Csla/Core/ExtendedBindingList.cs
  Source/Csla/Core/ObservableBindingList.cs
Labels: kind/enhancement

#4030 Blazor ViewModel with ManagedObjectLifetime save issue #4026
  Source/Csla.Blazor.Test/Fakes/FakeDataStorage.cs
  Source/Csla.Blazor.Test/Fakes/FakePerson.cs
  Source/Csla.Blazor.Test/ViewModelEditChildListSaveEditLevelTests.cs
  Source/Csla.Blazor/ViewModel.cs
Labels: kind/bug, area/Blazor

#4031 Blazor ViewModel with ManagedObjectLifetime save issue #4026
  Source/Csla.Blazor.Test/Fakes/FakeDataStorage.cs
  Source/Csla.Blazor.Test/Fakes/FakePerson.cs
  Source/Csla.Blazor.Test/ViewModelEditChildListSaveEditLevelTests.cs
  Source/Csla.Blazor/ViewModel.cs
Labels: kind/bug, area/Blazor

#4032 BusinessBase SaveAsync exception issue
  Source/Csla.Blazor.Test/Fakes/FakePerson.cs
  Source/Csla/BusinessBase.cs
Labels: kind/bug, area/Blazor

#4070 Remove local configuration
  Samples/BlazorExample/nuget.config
Labels: kind/technical debt
