Repository MarimerLLC/csla, pull requests merged in 2024-04, with the labels that each got.

#3818 typo Singelton
  Source/Csla.test/LazySingleton/LazySingletonTest.cs
Labels: kind/technical debt

#3805 ignore .idea from rider
  .gitignore
Labels: kind/enhancement

#3807 avoid redundant reflection type check
  Source/Csla/Server/DataPortal.cs
Labels: kind/technical debt

#3808 remove some redundant casts
  Source/Csla.Analyzers/Csla.Analyzers.Tests/CheckConstructorsAnalyzerPublicConstructorCodeFixTests.cs
  Source/Csla.AspNetCore/Blazor/ApplicationContextManagerBlazor.cs
  Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs
  Source/Csla.Web/Design/CslaDataSourceDesigner.cs
  Source/Csla.Web/Design/CslaDesignerDataSourceView.cs
  Source/Csla.Windows/BusyAnimation.cs
  Source/Csla.Xaml.Shared/BusyAnimation.cs
  Source/Csla.Xaml.Shared/PropertyStatus.cs
  Source/Csla.test/CommandBase/CommandBaseTest.cs
  Source/Csla.test/EditableRootList/EditableRootListTests.cs
  Source/Csla.test/Nullable/NullableObject.cs
  Source/Csla.test/RollBack/RollBackTests.cs
  Source/Csla.test/Serialization/SerializationTests.cs
  Source/Csla.test/SmartDate/SmartDateTests.cs
  Source/Csla.test/ValidationRules/ValidationTests.cs
  Source/Csla/BusinessBindingListBase.cs
  Source/Csla/BusinessListBase.cs
  Source/Csla/DynamicBindingListBase.cs
  Source/Csla/DynamicListBase.cs
  Source/Csla/Reflection/DynamicMethodHandlerFactory.cs
  Source/Csla/Serialization/Mobile/MobileFormatter.cs
  Source/Csla/Serialization/Mobile/SerializationInfo.cs
  Source/Csla/SmartDate.cs
Labels: kind/technical debt

#3809 user GetRequiredService to avoid null ref on variable use
  Source/Csla.Web.Mvc.Shared/CslaModelBinder.cs
Labels: kind/enhancement, kind/technical debt

#3810 avoid linq where length or count can be used
  Source/Csla.Analyzers/Csla.Analyzers/EvaluatePropertiesForSimplicityAnalyzer.cs
  Source/Csla.Web.Mvc.Shared/CslaModelBinder.cs
  Source/Csla.test/Reflection/GetConstructor.cs
  Source/Csla/Reflection/ServiceProviderMethodCaller.cs
Labels: kind/technical debt

#3813 simplify some linq
  Source/Csla.AspNetCore/RazorPages/PageModel.cs
  Source/Csla/Core/FieldManager/FieldDataManager.cs
  Source/Csla/Core/GraphMerger.cs
  Source/Csla/DataPortalClient/LocalProxyExtensions.cs
  Source/Csla/ReadOnlyBase.cs
  Source/Csla/Rules/AuthorizationRuleManager.cs
  Source/Csla/Rules/BrokenRulesCollection.cs
  Source/csla.netcore.test/DataPortal/RoutingTagTests.cs
Labels: kind/technical debt

#3814 make CustomParserReturnsDateTime assert the correct variable
  Source/Csla.test/SmartDate/SmartDateTests.cs
Labels: kind/bug

#3824 IDE0060 analyzer reports fixed
  Source/Csla.Web.Mvc.Shared/HtmlExtensions.cs
  Source/Csla.Xaml.Shared/PropertyInfo.cs
  Source/Csla/Core/ManagedObjectBase.cs
  Source/Csla/Data/DataMap.cs
  Source/Csla/DataPortalT.cs
  Source/Csla/Server/ChildDataPortal.cs
  Source/Csla/Server/DataPortalResult.cs
Labels: kind/technical debt

#3811 avoid incorrect as usage in PropertyStatus.popup_Loaded
  Source/Csla.Xaml.Shared/PropertyStatus.cs
Labels: kind/enhancement, kind/technical debt

#3806 use collection expressions
  Source/Csla.Analyzers/Csla.Analyzers.Tests/AssemblyReferences.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/BusinessRuleDoesNotUseAddMethodsOnContextAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/CheckConstructorsAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/DoesChildOperationHaveRunLocalAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/DoesOperationHaveAttributeAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/EvaluateManagedBackingFieldsAnalayzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/EvaluateOperationAttributeUsageAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/EvaluatePropertiesForSimplicityAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindBusinessObjectCreationAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindOperationsWithIncorrectReturnTypesAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindOperationsWithNonSerializableArgumentsAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindRefAndOutParametersInOperationsAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindSaveAssignmentIssueAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/IsBusinessObjectSerializableAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/IsCompleteCalledInAsynchronousBusinessRuleAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/IsOperationMethodPublicAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/TestHelpers.cs
  Source/Csla.Analyzers/Csla.Analyzers/Extensions/ITypeSymbolExtensions.cs
  Source/Csla.Channels.RabbitMq/ProxyListener.cs
  Source/Csla.Generators/cs/Csla.Generators.CSharp/AutoSerializable/SerializationPartialBuilder.cs
  Source/Csla.Generators/cs/Csla.Generators.CSharp/ExceptionExtensions.cs
  Source/Csla.Web/Design/CslaDataSourceDesigner.cs
  Source/Csla.Web/Design/ObjectSchema.cs
  Source/Csla.Windows/BusyAnimation.cs
  Source/Csla.Windows/ReadWriteAuthorization.cs
  Source/Csla.Xaml.Shared/CslaDataProvider.cs
  Source/Csla.Xaml.Shared/InvokeMethod.cs
  Source/Csla.Xaml.Shared/TriggerAction.cs
  Source/Csla.test/Authorization/AuthTests.cs
  Source/Csla.test/Basic/RootList.cs
  Source/Csla.test/ChildrenByInterface/ChildInterfaceTests.cs
  Source/Csla.test/DataPortal/ArrayTests.cs
  Source/Csla.test/Fakes/Server/BusyStatus/ItemWithAsynchRule.cs
  Source/Csla.test/MethodCaller/MethodCallerTests.cs
  Source/Csla.test/Reflection/GetConstructor.cs
  Source/Csla.test/Serialization/BinaryReaderWriterTestClass.cs
  Source/Csla.test/SortedBindingList/SortedBindingListTests.cs
  Source/Csla.test/ValidationRules/AsyncRuleRoot.cs
  Source/Csla.test/ValidationRules/HasAsyncRule.cs
  Source/Csla.test/ValidationRules/HasInvalidAsyncRule.cs
  Source/Csla.test/ValidationRules/RuleBaseClassesRoot.cs
  Source/Csla.test/ValidationRules/ValidationTests.cs
  Source/Csla/Core/FieldManager/FieldDataManager.cs
  Source/Csla/Core/GraphMerger.cs
  Source/Csla/Data/DataMapper.cs
  Source/Csla/Data/ObjectAdapter.cs
  Source/Csla/DataPortalT.cs
  Source/Csla/Reflection/DynamicMethodHandle.cs
  Source/Csla/Reflection/MethodCaller.cs
  Source/Csla/Reflection/ServiceProviderMethodCaller.cs
  Source/Csla/Rules/AuthorizationRuleManager.cs
  Source/Csla/Rules/AuthorizationRules.cs
  Source/Csla/Server/DataPortal.cs
  Source/csla.netcore.test/Basic/RootList.cs
  Source/csla.netcore.test/DataPortal/RoutingTagTests.cs
Labels: kind/enhancement, kind/technical debt

#3816 remove some redundant class bodies
  Source/Csla.Blazor.Test/Fakes/FakePersonEmailAddresses.cs
  Source/Csla.Windows/ConfigurationExtensions.cs
  Source/Csla.Xaml.Shared/ConfigurationExtensions.cs
  Source/Csla.test/Authorization/AuthTests.cs
  Source/Csla.test/Authorization/PermissionRootWithCriteria.cs
  Source/Csla.test/Basic/GenRoot.cs
  Source/Csla.test/BasicModern/ChildList.cs
  Source/Csla.test/BusinessListBase/ChildList.cs
  Source/Csla.test/ChildrenByInterface/ChildInterfaceTests.cs
  Source/Csla.test/DataPortal/LegacySplit.cs
  Source/Csla.test/DataPortal/Split.cs
  Source/Csla.test/DataPortal/SplitOverload.cs
  Source/Csla.test/DataPortalTestDatabaseDataSet.cs
  Source/Csla.test/Fakes/Server/CslaDataProvider/CustomerWithError.cs
  Source/Csla.test/Fakes/Server/DataPortal/Single.cs
  Source/Csla.test/IO/DPMethodOverloadTests.cs
  Source/Csla.test/MethodCaller/Caller3.cs
  Source/Csla.test/MethodCaller/CreateConstructorTests.cs
  Source/Csla.test/Serialization/SerializationTests.cs
  Source/Csla.test/ValidationRules/RuleURITests.cs
  Source/Csla/Configuration/Abstraction/ConnectionStringSettingsCollection.cs
  Source/Csla/Configuration/Fluent/CoreOptions.cs
  Source/Csla/Core/ICommandObject.cs
  Source/Csla/Core/IContextManagerLocal.cs
  Source/Csla/Core/IReadOnlyCollection.cs
  Source/Csla/DataPortalClient/IApplicationContextProvider.cs
  Source/Csla/DataPortalOperationAttributes.cs
  Source/Csla/IBusinessBase.cs
  Source/Csla/IBusinessListBase.cs
  Source/Csla/ICommandBase.cs
  Source/Csla/IReadOnlyBase.cs
  Source/Csla/IReadOnlyListBase.cs
  Source/Csla/NotUndoableAttribute.cs
  Source/Csla/ObjectAuthorizationRulesAttribute.cs
  Source/Csla/Rules/BrokenRulesTree.cs
  Source/Csla/RunLocalAttribute.cs
  Source/Csla/Security/ICslaPrincipal.cs
  Source/Csla/Serialization/AutoNonSerializedAttribute.cs
  Source/Csla/Serialization/AutoSerializableAttribute.cs
  Source/Csla/Serialization/AutoSerializedAttribute.cs
  Source/csla.netcore.test/Basic/GenRoot.cs
  Source/csla.netcore.test/BasicModern/ChildList.cs
  Source/csla.netcore.test/DataPortal/InheritedOperationTests.cs
  Source/csla.netcore.test/DataPortal/RoutingTagTests.cs
Labels: kind/technical debt

#3817 avoid some casting by using the correct value type on a dictionary
  Source/Csla.Blazor/ViewModel.cs
Labels: kind/technical debt

#3825 avoid list alloc in CslaDataProvider DoQuery
  Source/Csla.Xaml.Shared/CslaDataProvider.cs
Labels: kind/technical debt

#3826 remove redundant delegate constructor calls
  Source/Csla.Xaml.Shared/CslaDataProvider.cs
  Source/Csla.Xaml.Shared/DataDecoratorBase.cs
  Source/Csla.Xaml.Shared/PropertyStatus.cs
  Source/Csla.test/Basic/BasicTests.cs
  Source/Csla.test/EditableRootList/EditableRootListTests.cs
  Source/Csla.test/PropertyGetSet/PropertyGetSetTests.cs
  Source/Csla.test/RollBack/RollBackTests.cs
  Source/Csla.test/Serialization/SerializationTests.cs
  Source/Csla.test/Serialization/TestEventSink.cs
  Source/Csla.test/Serialization/nonSerializableEventHandler.cs
  Source/Csla.test/SortedBindingList/SortedBindingListTests.cs
  Source/Csla.test/ValidationRules/HasChildren.cs
  Source/Csla/Core/ExtendedBindingList.cs
  Source/Csla/Core/ObservableBindingList.cs
  Source/Csla/DynamicBindingListBase.cs
  Source/Csla/FilteredBindingList.cs
  Source/Csla/SortedBindingList.cs
  Source/Csla/Threading/BusyLock.cs
  Source/csla.netcore.test/Basic/BasicTests.cs
Labels: kind/technical debt

#3828 avoid some lambda alloc by merging some Where + Any
  Source/Csla.Analyzers/Csla.Analyzers/Extensions/SyntaxNodeExtensions.cs
  Source/Csla.Web.Mvc.Shared/CslaModelBinder.cs
  Source/Csla/Configuration/ConfigurationExtensions.cs
Labels: kind/technical debt

#3830 remove un used variables in ChildChangedTests
  Source/Csla.test/ChildChanged/ChildChangedTests.cs
Labels: kind/technical debt

#3827 use is to avoid duplicate cast
  Source/Csla.Channels.Grpc/GrpcPortal.cs
  Source/Csla.Channels.RabbitMq/RabbitMqPortal.cs
  Source/Csla.Generators/cs/Csla.Generators.CSharp/AutoSerializable/Discovery/ContainerDefinitionsExtractor.cs
  Source/Csla.Generators/cs/Csla.Generators.CSharp/AutoSerializable/Discovery/TypeDefinitionExtractor.cs
  Source/Csla.Web.Mvc.Shared/Server/Hosts/HttpPortal.cs
  Source/Csla.Web/CslaDataSourceView.cs
  Source/Csla.Windows/BindingSourceHelper.cs
  Source/Csla.Windows/BindingSourceRefresh.cs
  Source/Csla.Windows/CslaActionExtender.cs
  Source/Csla.Windows/CslaActionExtenderToolStrip.cs
  Source/Csla.Windows/ReadWriteAuthorization.cs
  Source/Csla.Xaml.Shared/PropertyInfo.cs
  Source/Csla.Xaml.Shared/PropertyStatus.cs
  Source/Csla.test/Basic/Child.cs
  Source/Csla/Core/TypeConverters/SmartDateConverter.cs
  Source/Csla/Data/DataServiceContextManager.cs
  Source/Csla/Data/ObjectAdapter.cs
  Source/Csla/FilteredBindingList.cs
  Source/Csla/Rules/BusinessRules.cs
  Source/Csla/Serialization/Mobile/CslaBinaryWriter.cs
  Source/Csla/Serialization/Mobile/CslaLegacyBinaryWriter.cs
  Source/Csla/Serialization/Mobile/SerializationInfo.cs
  Source/Csla/SmartDate.cs
  Source/Csla/SortedBindingList.cs
Labels: kind/technical debt

#3832 remove redundant private set
  Source/Csla.AspNetCore/ApplicationContextManagerHttpContext.cs
  Source/Csla.AspNetCore/Blazor/ApplicationContextManagerBlazor.cs
  Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs
  Source/Csla.Blazor.WebAssembly/ApplicationContextManager.cs
  Source/Csla.Blazor/ViewModel.cs
  Source/Csla.Channels.RabbitMq/RabbitMqPortal.cs
  Source/Csla.Web.Mvc.Shared/Controller.cs
  Source/Csla/Core/ApplicationContextAccessor.cs
  Source/Csla/Core/LoadManager/TaskLoader.cs
  Source/Csla/Data/SafeDataReader.cs
  Source/Csla/DataPortalResult.cs
  Source/Csla/MethodInfo.cs
  Source/Csla/PropertyInfo.cs
  Source/Csla/Reflection/LateBoundObject.cs
  Source/Csla/Reflection/MethodCacheKey.cs
  Source/Csla/Rules/AddObjectAuthorizationRulesContext.cs
  Source/Csla/Rules/AuthorizationContext.cs
  Source/Csla/Rules/BusinessRuleBase.cs
  Source/Csla/Rules/CommonRules.cs
  Source/Csla/Rules/RuleContext.cs
  Source/Csla/Server/Dashboard/Dashboard.cs
  Source/Csla/Server/DefaultDataPortalActivator.cs
  Source/Csla/Threading/BackgroundWorker.cs
  Source/Csla/Threading/ContextParams.cs
Labels: kind/technical debt

#3834 use some string interpolation
  Source/Csla.Web/CslaDataSource.cs
  Source/Csla.Web/Design/CslaDataSourceDesigner.cs
  Source/Csla.Windows/CslaActionExtender.cs
  Source/Csla.Windows/CslaActionExtenderToolStrip.cs
  Source/Csla.Xaml.Shared/BrokenRulesSeverityConverter.cs
  Source/Csla.Xaml.Shared/BusyAnimation.cs
  Source/Csla.Xaml.Shared/ErrorDialog.cs
  Source/Csla.Xaml.Shared/PropertyInfo.cs
  Source/Csla.Xaml.Shared/PropertyStatus.cs
  Source/Csla.test/MethodCaller/MethodCallerTests.cs
  Source/Csla.test/SmartDate/SmartDateTests.cs
  Source/Csla.test/ValidationRules/AsyncRuleRoot.cs
  Source/Csla.test/ValidationRules/RuleBaseClassesRoot.cs
  Source/Csla.test/ValidationRules/ValidationTests.cs
  Source/Csla/Core/BusinessBase.cs
  Source/Csla/DataPortalException.cs
  Source/Csla/DataPortalT.cs
  Source/Csla/ReadOnlyBase.cs
  Source/Csla/Rules/AuthorizationRule.cs
  Source/Csla/Rules/BusinessRuleBase.cs
  Source/Csla/Rules/BusinessRules.cs
  Source/Csla/Rules/CommonRules.cs
  Source/Csla/Serialization/Mobile/SerializationInfo.cs
  Source/Csla/Server/DataPortalTarget.cs
  Source/Csla/Server/FactoryDataPortal.cs
  Source/Csla/Server/ObjectFactoryAttribute.cs
Labels: kind/technical debt

#3836 use some raw strings
  Source/Csla.Analyzers/Csla.Analyzers.Tests/AsynchronousBusinessRuleInheritingFromBusinessRuleAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/AsynchronousBusinessRuleInheritingFromBusinessRuleChangeToBusinessRuleAsyncCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/BusinessRuleDoesNotUseAddMethodsOnContextAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/CheckConstructorsAnalyzerPublicConstructorCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/CheckConstructorsAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/ContainsInvocationExpressionWalkerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/DoesChildOperationHaveRunLocalAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/DoesChildOperationHaveRunLocalRemoveAttributeCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/DoesOperationHaveAttributeAddAttributeCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/DoesOperationHaveAttributeAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/EvaluateManagedBackingFieldsAnalayzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/EvaluateManagedBackingFieldsCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/EvaluateManagedBackingFieldsWalkerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/EvaluateOperationAttributeUsageAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/EvaluatePropertiesForSimplicityAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/Extensions/IMethodSymbolExtensionsTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/Extensions/ITypeSymbolExtensionsTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/Extensions/SyntaxNodeExtensionsTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindBusinessObjectCreationAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindGetOrReadInvocationsWalkerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindOperationsWithIncorrectReturnTypeResolveCorrectTypeCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindOperationsWithIncorrectReturnTypesAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindOperationsWithNonSerializableArgumentsAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindRefAndOutParametersInOperationsAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindSaveAssignmentIssueAnalyzerAddAssignmentCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindSaveAssignmentIssueAnalyzerAddAsyncAssignmentCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindSaveAssignmentIssueAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/FindSetOrLoadInvocationsWalkerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/IsBusinessObjectSerializableAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/IsBusinessObjectSerializableMakeSerializableCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/IsCompleteCalledInAsynchronousBusinessRuleAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/IsCompleteCalledInAsynchronousBusinessRuleRemoveCallCodeFixTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/IsOperationMethodPublicAnalyzerTests.cs
  Source/Csla.Analyzers/Csla.Analyzers.Tests/IsOperationMethodPublicMakeNonPublicCodeFixTests.cs
Labels: kind/technical debt

#3837 elide more asyncs
  Source/Csla.Blazor/State/StateManager.cs
  Source/Csla.test/Asserter.cs
  Source/Csla.test/DataAnnotations/DataAnnotationsTests.cs
  Source/Csla.test/Fakes/Server/CslaDataProvider/Customer.cs
  Source/Csla.test/Fakes/Server/Validation/RootThrowsException.cs
  Source/Csla.test/FieldManager/Async/Root.cs
  Source/Csla.test/FieldManager/Async/RootUpdateAllChildren.cs
  Source/Csla.test/ValidationRules/HasChildren.cs
  Source/Csla/BusinessBase.cs
  Source/Csla/BusinessBindingListBase.cs
  Source/Csla/BusinessListBase.cs
  Source/Csla/DataPortalT.cs
  Source/Csla/DynamicBindingListBase.cs
  Source/Csla/DynamicListBase.cs
  Source/Csla/ReadOnlyBase.cs
  Source/Csla/Server/ChildDataPortal.cs
  Source/Csla/Server/DataPortalTarget.cs
Labels: kind/technical debt

#3835 more collection expressions
  Source/Csla.Analyzers/Csla.Analyzers.Tests/AssemblyReferences.cs
  Source/Csla.AspNetCore/RazorPages/PageModel.cs
  Source/Csla.Blazor/ViewModel.cs
  Source/Csla.Channels.Grpc/GrpcPortal.cs
  Source/Csla.Channels.RabbitMq/WorkInProgress.cs
  Source/Csla.Web.Mvc.Shared/Server/Hosts/HttpPortalController.cs
  Source/Csla.Web/CslaDataSource.cs
  Source/Csla.Windows/BindingSourceRefresh.cs
  Source/Csla.Windows/CslaActionExtender.cs
  Source/Csla.Windows/CslaActionExtenderToolStrip.cs
  Source/Csla.Windows/ReadWriteAuthorization.cs
  Source/Csla.test/AppContext/TestContextManager.cs
  Source/Csla.test/ChildChanged/OptimizeChildChangedTests.cs
  Source/Csla/Core/FieldManager/FieldDataList.cs
  Source/Csla/Core/LoadManager/AsyncLoadManager.cs
  Source/Csla/Core/UndoableHandler.cs
  Source/Csla/Data/DataMap.cs
  Source/Csla/FilteredBindingList.cs
  Source/Csla/Reflection/MethodCaller.cs
  Source/Csla/Reflection/ServiceProviderMethodCaller.cs
  Source/Csla/Serialization/Mobile/MobileFormatter.cs
  Source/Csla/Serialization/Mobile/SerializationInfo.cs
  Source/Csla/Server/Dashboard/Dashboard.cs
  Source/Csla/Server/DataPortalMethodCache.cs
  Source/Csla/SortedBindingList.cs
Labels: kind/technical debt

#3839 Fix HttpProxy HttpClientHandler creation
  Source/Csla.test/HttpProxy/HttpProxyTests.cs
  Source/Csla/DataPortalClient/HttpProxy.cs
Labels: kind/bug

#3843 Fix build errors with UWP project
  Source/Csla.Xaml.Shared/ApplicationContextManager.cs
  Source/Csla.Xaml.Shared/ErrorEventArgs.cs
  Source/Csla.Xaml.Shared/PropertyInfo.cs
  Source/Csla.Xaml.Shared/ViewModelBase.cs
Labels: kind/bug

#3844 Update section on Android HttpClient configuration
  docs/Upgrading to CSLA 8.md
Labels: area/documentation

#3846 simplify some linq by merging where and count
  Source/Csla.test/DataAnnotations/DataAnnotationsTests.cs
  Source/Csla.test/Linq/LinqObservableCollectionTest.cs
  Source/Csla.test/ValidationRules/RuleBaseClassesTests.cs
Labels: kind/technical debt

#3847 avoid null checks by using is instead of as
  Source/Csla.Web.Mvc.Shared/CslaModelBinder.cs
  Source/Csla.Web.Mvc.Shared/ViewModelBase.cs
  Source/Csla.Windows/BindingSourceNode.cs
  Source/Csla.Windows/CslaActionExtender.cs
  Source/Csla.Windows/CslaActionExtenderToolStrip.cs
  Source/Csla.Windows/ReadWriteAuthorization.cs
  Source/Csla.Xaml.Shared/CslaDataProvider.cs
  Source/Csla.Xaml.Shared/CslaDataProviderCommandManager.cs
  Source/Csla.Xaml.Shared/DataDecoratorBase.cs
  Source/Csla.Xaml.Shared/ErrorDialog.cs
  Source/Csla.Xaml.Shared/InvokeMethod.cs
  Source/Csla.Xaml.Shared/ObjectStatus.cs
  Source/Csla.Xaml.Shared/PropertyInfo.cs
  Source/Csla.Xaml.Shared/PropertyStatus.cs
  Source/Csla.Xaml.Shared/TriggerAction.cs
  Source/Csla.test/DataAnnotations/DataAnnotationsTests.cs
  Source/Csla/Core/BusinessBase.cs
  Source/Csla/Core/ContextDictionary.cs
  Source/Csla/Core/ExtendedBindingList.cs
  Source/Csla/Core/ManagedObjectBase.cs
  Source/Csla/Core/ObservableBindingList.cs
  Source/Csla/Core/ReadOnlyBindingList.cs
  Source/Csla/Data/DataMapper.cs
  Source/Csla/Data/ObjectAdapter.cs
  Source/Csla/DataPortalT.cs
  Source/Csla/DynamicBindingListBase.cs
  Source/Csla/DynamicListBase.cs
  Source/Csla/FilteredBindingList.cs
  Source/Csla/LinqObservableCollection.cs
  Source/Csla/MethodInfo.cs
  Source/Csla/ReadOnlyBase.cs
  Source/Csla/Reflection/MethodCacheKey.cs
  Source/Csla/Reflection/Reflect.cs
  Source/Csla/Rules/AuthorizationRule.cs
  Source/Csla/Rules/AuthorizationRuleManager.cs
  Source/Csla/Serialization/Mobile/MobileFormatter.cs
  Source/Csla/Server/ObjectFactory.cs
  Source/Csla/SortedBindingList.cs
Labels: kind/technical debt

#3848 use some compound statements
  Source/Csla.test/PropertyGetSet/EditableGetSetBase.cs
  Source/Csla.test/PropertyGetSet/EditableGetSetTopBase.cs
  Source/Csla.test/Serialization/SerializationTests.cs
  Source/Csla/Reflection/MethodCacheKey.cs
  Source/Csla/Rules/ObjectRule.cs
  Source/Csla/Rules/ObjectRuleAsync.cs
  Source/Csla/Rules/PropertyRule.cs
  Source/Csla/Rules/PropertyRuleAsync.cs
  Source/Csla/Rules/RuleUri.cs
Labels: kind/technical debt

#3850 cleanup CompressionWebClient
  Source/Csla/DataPortalClient/HttpCompressionProxy.cs
Labels: kind/technical debt

#3851 use some null propagation
  Source/Csla.Blazor/PropertyInfo.cs
  Source/Csla.Web/CslaDataSource.cs
  Source/Csla.Windows/BindingSourceNode.cs
  Source/Csla.Windows/BindingSourceRefresh.cs
  Source/Csla.Windows/CslaActionExtender.cs
  Source/Csla.Windows/CslaActionExtenderToolStrip.cs
  Source/Csla.Xaml.Shared/CslaDataProvider.cs
  Source/Csla.Xaml.Shared/CslaDataProviderCommandManager.cs
  Source/Csla.Xaml.Shared/PropertyInfo.cs
  Source/Csla.Xaml.Shared/PropertyStatus.cs
  Source/Csla.test/GraphMerge/TestClasses.cs
  Source/Csla.test/Threading/BusyLockTests.cs
  Source/Csla/BusinessBase.cs
  Source/Csla/BusinessBindingListBase.cs
  Source/Csla/BusinessListBase.cs
  Source/Csla/Core/BindableBase.cs
  Source/Csla/Core/BusinessBase.cs
  Source/Csla/Core/ExtendedBindingList.cs
  Source/Csla/Core/FieldManager/FieldDataManager.cs
  Source/Csla/Core/LoadManager/AsyncLoadManager.cs
  Source/Csla/Core/ManagedObjectBase.cs
  Source/Csla/Core/ObservableBindingList.cs
  Source/Csla/Core/UndoableBase.cs
  Source/Csla/DynamicBindingListBase.cs
  Source/Csla/DynamicListBase.cs
  Source/Csla/FilteredBindingList.cs
  Source/Csla/ReadOnlyBase.cs
  Source/Csla/Serialization/Mobile/MobileFormatter.cs
  Source/Csla/Server/ChildDataPortal.cs
  Source/Csla/Server/SimpleDataPortal.cs
  Source/Csla/SmartDate.cs
  Source/Csla/SortedBindingList.cs
  Source/Csla/Threading/BackgroundWorker.cs
Labels: kind/technical debt

#3853 missing using on httpResponse
  Source/Csla/DataPortalClient/HttpProxy.cs
Labels: kind/bug

#3854 Outdated solution file and project file removed
  Source/Csla.test.Csla6.sln
  Source/Csla.test/csla.test.csproj
Labels: kind/technical debt

#3833 make private ApplicationContext instances a field
  Source/Csla.AspNetCore/RazorPages/PageModel.cs
  Source/Csla.Blazor/HasPermissionHandler.cs
  Source/Csla.Channels.Grpc/GrpcPortal.cs
  Source/Csla.Channels.RabbitMq/RabbitMqPortal.cs
  Source/Csla.Web.Mvc.Shared/CslaPermissionRequirement.cs
  Source/Csla.Web.Mvc.Shared/HasPermissionAttribute.cs
  Source/Csla.Web.Mvc.Shared/Server/Hosts/HttpPortal.cs
  Source/Csla.Web.Mvc.Shared/Server/Hosts/HttpPortalController.cs
  Source/Csla/Core/FieldManager/FieldDataManager.cs
  Source/Csla/Core/ObjectCloner.cs
  Source/Csla/Data/ConnectionManager.cs
  Source/Csla/Data/ConnectionManagerT.cs
  Source/Csla/Data/ContextManager.cs
  Source/Csla/Data/DataServiceContextManager.cs
  Source/Csla/Data/ObjectContextManager.cs
  Source/Csla/Data/ServiceClientManager.cs
  Source/Csla/Data/TransactionManager.cs
  Source/Csla/DataPortalT.cs
  Source/Csla/LazySingleton.cs
  Source/Csla/Reflection/LateBoundObject.cs
  Source/Csla/Reflection/ServiceProviderMethodCaller.cs
  Source/Csla/Rules/BusinessRules.cs
  Source/Csla/Serialization/Mobile/CslaBinaryReader.cs
  Source/Csla/Serialization/Mobile/CslaBinaryWriter.cs
  Source/Csla/Serialization/Mobile/MobileFormatter.cs
  Source/Csla/Server/ActiveAuthorizer.cs
  Source/Csla/Server/ChildDataPortal.cs
  Source/Csla/Server/DataPortal.cs
  Source/Csla/Server/DataPortalContext.cs
  Source/Csla/Server/DataPortalSelector.cs
  Source/Csla/Server/FactoryDataPortal.cs
  Source/Csla/Server/ObjectFactoryLoader.cs
  Source/Csla/Server/SimpleDataPortal.cs
  Source/Csla/Threading/BackgroundWorker.cs
  Source/Csla/Threading/ContextParams.cs
Labels: kind/technical debt

#3858 Make unit tests "run all" able from within VS
  Source/Csla.TestHelpers/TestResults.cs
  Source/Csla.test/DataPortal/DataPortalTests.cs
Labels: kind/technical debt

#3859 Run tests in CI build
  .github/workflows/ci.yaml
  Source/Csla.test/AppContext/AppContextTests.cs
  Source/Csla.test/Authorization/AuthTests.cs
  Source/Csla.test/BasicModern/BasicModernTests.cs
  Source/Csla.test/DPException/DataPortalExceptionTests.cs
  Source/Csla.test/DataPortal/DataPortalTests.cs
  Source/Csla.test/DataPortal/DisposeScopeTest.cs
  Source/Csla.test/DataPortal/InterceptorTests.cs
  Source/Csla.test/SafeDataReader/SafeDataReaderTests.cs
  Source/Csla.test/ValidationRules/RuleBaseClassesTests.cs
  Source/TraceAndTestImpact.testsettings
  Source/readme.md
  Source/test.runsettings
Labels: kind/technical debt

#3860 missing using on HttpRequestMessage
  Source/Csla/DataPortalClient/HttpProxy.cs
Labels: kind/bug, kind/technical debt

#3861 move to using declarations
  Source/Csla.Analyzers/Csla.Analyzers.Tests/TestHelpers.cs
  Source/Csla.Generators/cs/Csla.Generators.CSharp/AutoSerializable/SerializationPartialBuilder.cs
  Source/Csla.test/SafeDataReader/SafeDataReaderTests.cs
  Source/Csla.test/ValidationRules/ValidationTests.cs
  Source/Csla/DataPortalClient/HttpProxy.cs
  Source/Csla/Serialization/Mobile/CslaBinaryReader.cs
  Source/Csla/Serialization/Mobile/CslaBinaryWriter.cs
  Source/Csla/Serialization/Mobile/CslaLegacyBinaryReader.cs
  Source/Csla/Serialization/Mobile/CslaLegacyBinaryWriter.cs
  Source/Csla/Serialization/Mobile/CslaXmlBinaryReader.cs
  Source/Csla/Serialization/Mobile/CslaXmlBinaryWriter.cs
  Source/Csla/Serialization/Mobile/CslaXmlReader.cs
  Source/Csla/Serialization/Mobile/CslaXmlWriter.cs
  Source/Csla/Serialization/Mobile/MobileFormatter.cs
  Source/Csla/Server/TransactionalDataPortal.cs
  releasenotes.md
Labels: kind/technical debt

#3881 Re enable CommandBaseTest
  Source/Csla.test/CommandBase/CommandBaseTest.cs
Labels: kind/technical debt

#3891 #3802 - replace null parameter with containingType
  Source/Csla.test/PropertyInfo/PropertyInfoRoot.cs
  Source/Csla.test/PropertyInfo/PropertyInfoTests.cs
  Source/Csla/PropertyInfo.cs
Labels: kind/bug, kind/technical debt
