Repository MarimerLLC/csla, pull requests merged in 2024-05, with the labels that each got.

#3904 Remove unnecessary private set; and make a field readonly.
  Source/Csla.Xaml.Shared/PropertyInfo.cs
  Source/Csla/Configuration/Fluent/CslaOptions.cs
Labels: kind/enhancement

#3903 #3897 Fix error catching in blazor ApplicationContextManagers
  Source/Csla.AspNetCore/Blazor/ApplicationContextManagerBlazor.cs
  Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs
Labels: kind/bug, flag/breaking change

#3909 Resolve build issues in csla.test.sln
  Source/Csla.test/Csla.Tests.csproj
  Source/Csla.test/DataPortalTestDatabaseDataSet.Designer.cs
  Source/Csla.test/DataPortalTestDatabaseDataSet.cs
  Source/Csla.test/DataPortalTestDatabaseDataSet.xsc
  Source/Csla.test/DataPortalTestDatabaseDataSet.xsd
  Source/Csla.test/DataPortalTestDatabaseDataSet.xss
  Source/Csla.test/packages.config.old
  Source/csla.test.sln
Labels: kind/technical debt

#3912 Remove types marked with obsolete and error=true
  Source/Csla/Configuration/Fluent/DataOptions.cs
  Source/Csla/Data/ConnectionManager.cs
  Source/Csla/Data/ConnectionManagerT.cs
  Source/Csla/Data/ContextManager.cs
  Source/Csla/Data/DataServiceContextManager.cs
  Source/Csla/Data/TransactionManager.cs
  Source/Csla/Threading/BackgroundWorker.cs
Labels: flag/breaking change, kind/technical debt

#3914 Improve serializer registration
  Source/Csla/Configuration/Fluent/SerializationOptions.cs
  Source/csla.netcore.test/Serialization/SerializationTests.cs
Labels: kind/enhancement, flag/breaking change, kind/technical debt

#3948 remove some redundant parens
  Source/Csla.Blazor.WebAssembly/Configuration/ConfigurationExtensions.cs
  Source/Csla.test/DataMapper/DataMapperTests.cs
  Source/Csla.test/SmartDate/SmartDateTests.cs
  Source/Csla.test/ValidationRules/HasLambdaRules.cs
  Source/Csla/Configuration/ConfigurationExtensions.cs
  Source/Csla/Rules/AuthorizationRuleManager.cs
  Source/Csla/Rules/BusinessRuleManager.cs
  Source/Csla/Rules/BusinessRules.cs
  Source/Csla/Rules/BusinessRulesExtensions.cs
  Source/Csla/Rules/RuleContext.cs
  Source/Csla/Server/DataPortalTarget.cs
Labels: kind/technical debt

#3949 move to some using declarations
  Source/Csla.test/SafeDataReader/SafeDataReaderTests.cs
  Source/Csla/Serialization/Mobile/MobileFormatter.cs
Labels: kind/technical debt

#3951 remove some redundant usings
  Source/Csla.Analyzers/Csla.Analyzers.Tests/TestHelpers.cs
  Source/Csla.AspNetCore/Blazor/ApplicationContextManagerInMemory.cs
  Source/Csla.Blazor.WebAssembly.Tests/SessionManagerTests.cs
  Source/Csla.Blazor.WebAssembly/State/SessionManager.cs
  Source/Csla.TestHelpers/TestResults.cs
  Source/Csla.Web.Mvc.Shared/Controller.cs
  Source/Csla.Web.Mvc.Shared/HasPermissionAttribute.cs
  Source/Csla.Web.Mvc.Shared/ViewModelBase.cs
  Source/Csla.Xaml.Shared/ErrorEventArgs.cs
  Source/Csla.test/ValidationRules/OutputCoercionTest.cs
  Source/Csla/ReadOnlyBase.cs
  Source/Csla/Reflection/DynamicMethodHandlerFactory.cs
  Source/Csla/Serialization/BinaryFormatterWrapper.cs
Labels: kind/technical debt

#3952 use some nameof expressions
  Source/Csla/Core/BusinessBase.cs
  Source/Csla/DataPortalOperationExtensions.cs
  Source/Csla/ReadOnlyBase.cs
  Source/Csla/Reflection/DynamicMethodHandlerFactory.cs
  Source/Csla/Reflection/MethodCaller.cs
  Source/Csla/Reflection/Reflect.cs
  Source/Csla/Rules/RuleResult.cs
  Source/Csla/Server/DataPortal.cs
Labels: kind/technical debt

#3892 Fix ruleSet parameter omission in AddRule overloads
  Source/Csla/Rules/BusinessRulesExtensions.cs
Labels: pr/TestsRequested

#3957 Create rabbitmq readme.md
  Source/Csla.Channels.RabbitMq/readme.md
Labels: kind/technical debt

#3978 Add exception message for string.IsNullOrWhiteSpace() exception
  Source/Csla/Properties/Resources.Designer.cs
  Source/Csla/Properties/Resources.resx
Labels: kind/enhancement
